UPDATE PROCESSOCOTACAO PC SET CODIGOUNIDADEMEDIDA = 
(SELECT UNIDADEMEDIDA FROM 
PROCESSOCOTACAOMATERIAL PCM INNER JOIN REQUISICAOCOMPRA RC
ON PCM.IDREQUISICAOCOMPRA = RC.ID
WHERE PC.ID = PCM.ID)
WHERE CODIGOUNIDADEMEDIDA IS NULL;
COMMIT;

