DROP TABLE cotacaoimposto;
DROP TABLE fornecedorparticipante;
DROP TABLE cotacao;
DROP TABLE requisicaocompra;
DROP TABLE PROCESSOCOTACAOMATERIAL;
DROP TABLE PROCESSOCOTACAO;
DROP TABLE PRODUTOFORNECEDOR;
DROP TABLE PRODUTO;
DROP TABLE FORNECEDOR;
DROP TABLE CONDICAOPAGAMENTO;
DROP TABLE incoterm;
DROP TABLE ITINERARIO;
DROP TABLE IVA;
DROP TABLE usuarioperfil;
DROP TABLE Usuario;
DROP TABLE UNIDADEMEDIDA;

